"""new teble last_id

Revision ID: 5ac9a6a2a974
Revises: b3a3778a6c79
Create Date: 2024-05-22 00:16:43.185807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac9a6a2a974'
down_revision: Union[str, None] = 'b3a3778a6c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_id')
    # ### end Alembic commands ###
